version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: 8ubble8uddy/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: 8ubble8uddy/foodgram_frontend:latest
    volumes:
      - frontend_value:/app/result_build/build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - /etc/letsencrypt/:/etc/nginx/ssl/
      - frontend_value:/usr/share/nginx/html/
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/mediafiles/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  frontend_value: